import { useState } from 'react';
import { QUESTIONS, dateLabel } from '../questionData.js';
import { Header, Icon, Empty, Section } from '../components/UI.jsx';

export default function Records({ answers, go, openQuestion }) {
  const [filter, setFilter] = useState('전체 기록');
  const answered = QUESTIONS.filter(q => answers[q.id]?.submitted);
  const completed = answered.filter(q => answers[q.id].completed);
  const visible = answered.filter(q => filter === '전체 기록' || (filter === '성찰 완료' ? answers[q.id].completed : answers[q.id].sharedWith.length));
  return <><Header title="나의 기록" subtitle="작은 선택들이 모여 나를 알려줘요." /><div className="record-summary"><span className="empty-icon"><Icon name="leaf" size={28} /></span><div><h2>{answered.length}번의 선택, {completed.length}번의 성찰</h2><p className="sub">조금씩 넓어지는 생각의 발자국</p></div></div><Section title="9월의 발자국"><div className="calendar" aria-label="2026년 9월 답변 기록">{['일', '월', '화', '수', '목', '금', '토'].map(d => <span className="weekday" key={d}>{d}</span>)}<span /><span />{Array.from({ length: 30 }, (_, i) => { const day = i + 1; const q = QUESTIONS.find(q => Number(q.date.slice(8)) === day); const done = q && answers[q.id]?.submitted; return <button key={day} disabled={!q} aria-label={`9월 ${day}일${q ? ` ${q.title}${done ? ' 답변 완료' : ' 미답변'}` : ' 질문 없음'}`} className={`${done ? 'has-answer' : ''} ${day === 25 ? 'calendar-today' : ''}`} onClick={() => openQuestion(q.id)}>{day}{done && <span />}</button>; })}</div><p className="footnote">색칠한 날은 답변한 날이에요. 질문이 있는 날짜를 눌러보세요.</p></Section><button className="report-link" onClick={() => go('report')}><span><strong>내 생각의 방향 살펴보기</strong><small>선택에 담긴 주제를 돌아봐요</small></span><Icon name="arrow" /></button><div className="filter-tabs">{['전체 기록', '성찰 완료', '공유한 기록'].map(f => <button key={f} aria-pressed={f === filter} className={f === filter ? 'selected' : ''} onClick={() => setFilter(f)}>{f}</button>)}</div>{visible.length ? visible.map(q => <button className="record-card" key={q.id} onClick={() => go(`records/${q.id}`)}><div className="row"><span className="eyebrow">{dateLabel(q.date)} · {q.category}</span><span className="status answered">{answers[q.id].completed ? '성찰 완료' : '답변 완료'}</span></div><h3>{q.title}</h3><p>{q.choices.find(c => c.id === answers[q.id].sel)?.short}</p>{answers[q.id].note && <p className="sub record-note">{answers[q.id].note}</p>}<span className="text-link">기록 자세히 보기<Icon name="arrow" size={15} /></span></button>) : <Empty title={answered.length ? '아직 해당 기록이 없어요' : '첫 번째 갈래를 남겨보세요'} body="질문에 답하고 성찰하면 이곳에 차곡차곡 쌓여요." label="질문 만나보기" onClick={() => go('archive')} />}</>;
}
